export const additionalMasterNodes = [
  {
    code: "NODE_ADD_01",
    title: "The Doubling Step Series",
    tier: "foundation",
    domain: "algorithms",
    story: "An encrypted sequence was captured during network reconnaissance. Each successive number follows a strict arithmetic progression.",
    clue_text: "Find the missing number in the sequence:\n3, 8, 18, 38, 78, ?",
    payload: "SEQUENCE: 3, 8, 18, 38, 78, ?\nTASK: Compute the next term in this sequence.",
    answer: "158",
    aliases: ["158"],
    near_misses: { "156": "Check the offset: each step multiplies by 2 and adds 2 (not 0)!", "79": "The sequence is strictly increasing." },
    hints: [
      "Look at the difference between consecutive terms: 5, 10, 20, 40...",
      "Notice that 3 * 2 + 2 = 8.",
      "8 * 2 + 2 = 18.",
      "18 * 2 + 2 = 38.",
      "38 * 2 + 2 = 78.",
      "Apply the pattern: 78 * 2 + 2.",
      "78 * 2 + 2 = 156 + 2 = 158."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_02",
    title: "The Drifting Chronometer",
    tier: "foundation",
    domain: "systems",
    story: "A vintage quartz clock in the telemetry lab experiences an oscillator frequency drop, losing exactly 10 minutes every real hour.",
    clue_text: "A clock loses 10 minutes every hour. At exactly noon (12:00 PM), it is set correctly.\n\nWhen the real time is 6:00 PM on the same day, what time does this clock show?",
    payload: "DRIFT: -10 minutes per real hour\nSTART: 12:00 PM (Noon)\nREAL DURATION: 6 hours (at 6:00 PM)\nTASK: Output the clock's displayed time (e.g., 5 PM or 5:00 PM).",
    answer: "5 pm",
    aliases: ["5 pm", "5:00 pm", "5pm", "5:00pm", "17:00", "5"],
    near_misses: { "7 pm": "The clock loses time, so it runs slower than real time, not faster!", "5:10 pm": "10 minutes lost per hour over 6 hours equals 60 minutes total loss." },
    hints: [
      "The clock loses 10 minutes every real hour.",
      "From 12:00 PM noon to 6:00 PM is exactly 6 hours.",
      "Total minutes lost = 6 * 10 = 60 minutes.",
      "60 minutes lost is equivalent to 1 full hour behind.",
      "Subtract 1 hour from 6:00 PM.",
      "6:00 PM - 1 hour = 5:00 PM.",
      "Answer: 5 PM."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_03",
    title: "The Boy Who Lived",
    tier: "foundation",
    domain: "sleuth",
    story: "An investigator's pinboard contains four cryptic symbols: a flash of lightning, a robed wizard, a snowy owl, and a jagged scar.",
    clue_text: "Four iconic symbols are pinned together:\n⚡ Lightning\n🧙 Wizard\n🦉 Owl\n⚡ Scar\n\nWhich legendary literary and cinematic character connects all four clues?",
    payload: "CLUES: Lightning, Wizard, Owl, Scar\nTASK: Identify the famous titular character (First and Last name).",
    answer: "harry potter",
    aliases: ["harry potter", "harry", "potter"],
    near_misses: { "voldemort": "The lightning bolt scar and the pet owl Hedwig belong to the protagonist!", "merlin": "Merlin didn't have a lightning scar or Hedwig the owl." },
    hints: [
      "The owl is a familiar delivery companion named Hedwig.",
      "The lightning bolt scar is marked upon his forehead.",
      "He attends a famous school of Witchcraft and Wizardry.",
      "The author of the series is J.K. Rowling.",
      "He belongs to Gryffindor house.",
      "The initials are H.P.",
      "Answer: Harry Potter."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_04",
    title: "Quadratic Sum Product Operator",
    tier: "foundation",
    domain: "algorithms",
    story: "A custom arithmetic logic operator defined in a specialized arithmetic coprocessor computes non-standard values.",
    clue_text: "Observe the operator pattern:\n2 + 3 = 19\n3 + 4 = 37\n4 + 5 = 61\n5 + 6 = ?\n\nWhat is the value of 5 + 6 under this operator?",
    payload: "2 + 3 = 19\n3 + 4 = 37\n4 + 5 = 61\n5 + 6 = ?\nTASK: Determine the missing integer.",
    answer: "91",
    aliases: ["91"],
    near_misses: { "61": "Apply the rule to 5 and 6.", "85": "Remember to include the product term a * b!" },
    hints: [
      "Both operands are squared, but there is also a third term.",
      "For 2 + 3: 2² + 3² = 4 + 9 = 13. The result is 19. Notice 19 - 13 = 6 = 2 * 3.",
      "The formula is: a² + b² + (a * b).",
      "Test with 3 + 4: 3² + 4² + (3*4) = 9 + 16 + 12 = 37. Correct!",
      "Test with 4 + 5: 4² + 5² + (4*5) = 16 + 25 + 20 = 61. Correct!",
      "Now compute for 5 + 6: 5² + 6² + (5*6).",
      "25 + 36 + 30 = 91."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_05",
    title: "The Hexad Connection",
    tier: "foundation",
    domain: "verbal",
    story: "Three disparate entities in recreation, sports, and music share an identical structural number.",
    clue_text: "Consider the following three facts:\n1. A standard snooker table has ___ pockets.\n2. In ice hockey, each team normally has ___ players on the ice (including the goalie).\n3. A traditional acoustic or electric guitar has ___ strings.\n\nWhat single integer connects all three clues?",
    payload: "CLUE 1: Snooker table pocket count\nCLUE 2: Ice hockey on-ice team size\nCLUE 3: Standard guitar string count\nTASK: Enter the integer.",
    answer: "6",
    aliases: ["6", "six"],
    near_misses: { "5": "A guitar has 6 strings (E A D G B E), and snooker tables have 6 pockets!", "8": "Count the pockets: 4 corner + 2 middle = 6." },
    hints: [
      "How many pockets are on a billiard/snooker table? 4 corner pockets and 2 side pockets.",
      "How many strings are on a standard guitar? E, A, D, G, B, E.",
      "How many players per team skate on the ice at one time in regulation hockey?",
      "All three quantities are identical.",
      "4 corners + 2 center pockets = 6 pockets.",
      "The number is six.",
      "Answer: 6."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_06",
    title: "Lexicographical Monotonicity",
    tier: "foundation",
    domain: "verbal",
    story: "A linguistic anomaly hidden inside the English numeral nomenclature.",
    clue_text: "What is the only positive number whose letters appear in strict alphabetical order when spelled out in English?",
    payload: "CRITERION: Letters in strictly non-decreasing alphabetical order (A to Z)\nLANGUAGE : English spelling\nTASK     : Write the spelled number word.",
    answer: "forty",
    aliases: ["forty", "40"],
    near_misses: { "fourteen": "In 'fourteen', 'u' comes after 'o', but 'r' comes before 'u'.", "four": "In 'four', 'u' comes after 'r'." },
    hints: [
      "Note the spelling: it is spelled without a 'u'.",
      "F - O - R - T - Y.",
      "Check letter indices: F (6), O (15), R (18), T (20), Y (25).",
      "6 < 15 < 18 < 20 < 25.",
      "It represents 4 tens.",
      "Spelled: F-O-R-T-Y.",
      "Answer: forty."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_07",
    title: "Alphabetic Gematria Sum",
    tier: "foundation",
    domain: "cryptography",
    story: "A simple A1Z26 cipher sums each letter's 1-indexed alphabetical position.",
    clue_text: "If:\nCAT = 24  (3 + 1 + 20)\nDOG = 26  (4 + 15 + 7)\nBAT = 23  (2 + 1 + 20)\nCOW = 41  (3 + 15 + 23)\n\nWhat is the value of FOX?",
    payload: "CAT = 24\nDOG = 26\nBAT = 23\nCOW = 41\nFOX = ?\nTASK: Compute the sum for FOX.",
    answer: "45",
    aliases: ["45"],
    near_misses: { "44": "Check X's position: X is the 24th letter of the alphabet!", "46": "F=6, O=15, X=24." },
    hints: [
      "Convert each letter to its alphabetical rank (A=1, B=2, ..., Z=26).",
      "Letter F is position 6.",
      "Letter O is position 15.",
      "Letter X is position 24.",
      "Sum them together: 6 + 15 + 24.",
      "6 + 15 = 21; 21 + 24 = 45.",
      "Answer: 45."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_08",
    title: "Phonetic Duet Season",
    tier: "foundation",
    domain: "verbal",
    story: "A word puzzle based on cryptic phonetic wordplay.",
    clue_text: "Guess the word / season represented by:\n\nR + R",
    payload: "CLUE: R + R\nTASK: Decrypt the wordplay into a well-known English noun / season.",
    answer: "summer",
    aliases: ["summer", "sum of r", "some r"],
    near_misses: { "spring": "R + R is a sum of Rs -> 'Sum R' -> Summer!", "winter": "Think about how you speak R + R aloud." },
    hints: [
      "What mathematical operation combines two terms? A sum.",
      "You are taking the 'sum' of 'R'.",
      "Say 'Sum of R' or 'Some R' quickly aloud.",
      "It sounds like a warm season of the year.",
      "The season between Spring and Autumn.",
      "S-U-M-M-E-R.",
      "Answer: summer."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_09",
    title: "Visual Rebus: Solidification",
    tier: "foundation",
    domain: "lateral",
    story: "An intercepted visual transmission shows a rebus with corporate, database, and structural overtones.",
    clue_text: "Inspect the provided image rebus and determine the single English noun it depicts.",
    payload: "REBUS IMAGE: /puzzles/puzzle_img_1.png\nTASK: Guess the single English word represented by the rebus.",
    media_type: "image",
    media_url: "/puzzles/puzzle_img_1.png",
    answer: "consolidation",
    aliases: ["consolidation", "consolidate"],
    near_misses: { "solid": "The rebus represents the full noun: Consolidation!", "consolidation phase": "Just the single word." },
    hints: [
      "Examine the visual elements in the graphic.",
      "It represents combining multiple entities or strengthening into a single unit.",
      "In finance and accounting, it refers to combining balance sheets.",
      "In freight, it means grouping cargo.",
      "Starts with 'CON' and ends with 'ATION'.",
      "Consolidation.",
      "Answer: consolidation."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_10",
    title: "The Volunteer State Orthography",
    tier: "foundation",
    domain: "verbal",
    story: "A geographic name famous for its rhythmic double consonants and vowels.",
    clue_text: "I am a US state whose name is spelled with four distinct letters (E, I, N, S, T) containing four E's, two N's, and two pairs of double consonants.\n\nWhich US state am I?",
    payload: "CLUE: 4 E's, 2 N's, 2 S's, starts with T\nTASK: Name of the state (lowercase).",
    answer: "tennessee",
    aliases: ["tennessee"],
    near_misses: { "mississippi": "Mississippi has M, I, S, P (no E's)!", "alabama": "Count the letters: T-E-N-N-E-S-S-E-E." },
    hints: [
      "Capital is Nashville.",
      "Known as the Volunteer State.",
      "Contains the syllables: Ten - nes - see.",
      "Spelled: T-E-N-N-E-S-S-E-E.",
      "It is home to the Grand Ole Opry and Graceland.",
      "Nine letters total: T-E-N-N-E-S-S-E-E.",
      "Answer: tennessee."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_11",
    title: "Wason Selection Task",
    tier: "foundation",
    domain: "algorithms",
    story: "A classic cognitive psychology and logic benchmark formulated by Peter Cathcart Wason in 1966.",
    clue_text: "You are shown four cards on a table: [ A ]   [ D ]   [ 4 ]   [ 7 ]\nEach card has a letter on one side and an integer on the other.\n\nRULE: \"If a card has a vowel on one side, then it must have an even number on the other side.\"\n\nWhich minimum cards MUST you turn over to definitively test whether this rule is violated?",
    payload: "CARDS: A, D, 4, 7\nRULE : Vowel -> Even\nTASK : Specify the cards to turn over (format: 'A and 7' or 'A, 7').",
    answer: "a and 7",
    aliases: ["a and 7", "a, 7", "7 and a", "a 7", "7, a", "card a and card 7"],
    near_misses: { "a and 4": "Card 4 does NOT need to be turned! The rule does not say even numbers can only have vowels!", "all": "D is irrelevant, and 4 cannot violate the conditional (P -> Q)." },
    hints: [
      "Consider the logical conditional: P implies Q (Vowel -> Even).",
      "A conditional is falsified ONLY when P is true and Q is false (Vowel and Odd).",
      "Card [A] is a vowel (P). If its other side is odd, the rule is broken. So we must test A.",
      "Card [D] is a consonant (not P). A consonant can have any number. No violation possible.",
      "Card [4] is even (Q). If it has a consonant, the rule is not violated. We don't need to test 4.",
      "Card [7] is odd (not Q). If its other side is a vowel, the rule is broken! So we must test 7.",
      "Answer: A and 7."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_12",
    title: "The Outlaw of Sherwood Rebus",
    tier: "foundation",
    domain: "verbal",
    story: "A typographical container cipher holding a legendary English folklore hero.",
    clue_text: "Decipher the hidden name inside this typographical arrangement:\n\nHOrobOD",
    payload: "STRING: HOrobOD\nTASK: Extract the full character name.",
    answer: "robin hood",
    aliases: ["robin hood", "robinhood"],
    near_misses: { "robin": "Include both parts of the legendary archer's name!", "hood": "Look at the letters inside: 'rob' in 'HOOD'." },
    hints: [
      "Notice the casing: 'rob' is inside 'HO' and 'OD'.",
      "HO + OD = HOOD.",
      "The letters 'rob' are IN 'HOOD'.",
      "'rob' in 'hood' -> Robin Hood!",
      "The heroic outlaw of Sherwood Forest who steals from the rich and gives to the poor.",
      "Robin Hood.",
      "Answer: robin hood."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_13",
    title: "The Vessel of Exploration",
    tier: "foundation",
    domain: "sleuth",
    story: "The name of Captain Cook's third voyage vessel, Robert Falcon Scott's Antarctic ship, a NASA space shuttle, and a major educational TV network.",
    clue_text: "What historic nine-letter word connects Captain Scott's British National Antarctic Expedition (1901), NASA Space Shuttle orbiter OV-103, and the cable channel home of Shark Week?",
    payload: "CLUE 1: RRS ... (1901 Scott polar ship)\nCLUE 2: NASA Space Shuttle orbiter OV-103\nCLUE 3: Science & nature documentary channel\nTASK: Identify the shared word.",
    answer: "discovery",
    aliases: ["discovery", "space shuttle discovery", "hms discovery"],
    near_misses: { "endeavour": "Scott's ship and the Shark Week television channel share the name Discovery!", "atlantis": "Atlantis is not a documentary cable channel." },
    hints: [
      "It means the act of finding or uncovering something previously unknown.",
      "Space Shuttle that flew 39 missions including deploying the Hubble Space Telescope.",
      "Discovery Channel.",
      "RRS Discovery carried Scott and Shackleton to Antarctica.",
      "Starts with 'Disco...'.",
      "D-I-S-C-O-V-E-R-Y.",
      "Answer: discovery."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_14",
    title: "Set-Theoretic Mobile Strategy",
    tier: "foundation",
    domain: "cryptography",
    story: "A mathematical pseudo-code expression represents a globally popular mobile strategy game developed by Supercell.",
    clue_text: "Interpret this symbolic expression:\n\nC ∩ ( C ( LAN , LAN ) )\n\n[Clue: C + lash of C + lans]",
    payload: "EXPRESSION: C ∩ ( C ( LAN , LAN ) )\nTASK: Name the massive multiplayer mobile game by Supercell.",
    answer: "clash of clans",
    aliases: ["clash of clans", "coc"],
    near_misses: { "clash royale": "This specific title features town halls, barbarians, and clan wars: Clash of Clans!", "brawl stars": "Supercell's game featuring 'Clans'." },
    hints: [
      "Notice the intersection symbol ∩ (clash / clash of).",
      "'C' + 'lash' + 'of' + 'C' + 'lans'.",
      "Mobile strategy game launched in 2012 by Supercell.",
      "Players build villages, train troops, and fight in Clan Wars.",
      "Initials: CoC.",
      "Clash of Clans.",
      "Answer: clash of clans."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_15",
    title: "Cell Block Polybius Inscription",
    tier: "foundation",
    domain: "cryptography",
    story: "A prisoner in a high-security citadel carved a 4-coordinate cipher into the stone wall using a standard 5x5 Polybius square where 'J' is excluded.",
    clue_text: "A 5x5 grid with rows 1-5 and cols 1-5 maps letters A-Z (excluding J):\nRow 1: A(11) B(12) C(13) D(14) E(15)\nRow 2: F(21) G(22) H(23) I(24) K(25)\nRow 3: L(31) M(32) N(33) O(34) P(35)\nRow 4: Q(41) R(42) S(43) T(44) U(45)\nRow 5: V(51) W(52) X(53) Y(54) Z(55)\n\nDecrypt the coordinate sequence: 12 - 31 - 45 - 15.",
    payload: "CIPHER: 12 - 31 - 45 - 15\nGRID  : 5x5 Polybius (J omitted)\nTASK  : Decrypt into a 4-letter color / plaintext word.",
    answer: "blue",
    aliases: ["blue"],
    near_misses: { "bleu": "Check 45: Row 4 Col 5 is U, and 15: Row 1 Col 5 is E -> B L U E." },
    hints: [
      "12 = Row 1, Column 2. In Row 1 (A B C D E), the second letter is B.",
      "31 = Row 3, Column 1. In Row 3 (L M N O P), the first letter is L.",
      "45 = Row 4, Column 5. In Row 4 (Q R S T U), the fifth letter is U.",
      "15 = Row 1, Column 5. In Row 1 (A B C D E), the fifth letter is E.",
      "Combine the letters: B - L - U - E.",
      "The color of the sky.",
      "Answer: blue."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_16",
    title: "The Vault Mastermind Triad",
    tier: "intermediate",
    domain: "algorithms",
    story: "A safe with a 3-digit combination lock was tested by an intelligence operative who left six diagnostic probes.",
    clue_text: "Deduce the unique 3-digit code from these six clues:\n- 682 : One digit is correct and well placed.\n- 614 : One digit is correct but wrong place.\n- 206 : Two digits are correct but both are in the wrong places.\n- 738 : Nothing is correct.\n- 790 : One digit is correct but wrong place.\n- 431 : One digit is correct but wrong place.\n\nWhat is the 3-digit code?",
    payload: "CLUES:\n682 -> 1 correct, well-placed\n614 -> 1 correct, wrong-placed\n206 -> 2 correct, wrong-placed\n738 -> 0 correct\n790 -> 1 correct, wrong-placed\n431 -> 1 correct, wrong-placed\nTASK: Enter the 3-digit code.",
    answer: "102",
    aliases: ["102"],
    near_misses: { "042": "From clue 738, 7, 3, 8 are eliminated. Check clue 682!", "012": "Check digit placement: 0 must be in the middle from clues 206 and 790!" },
    hints: [
      "From '738: Nothing is correct', eliminate 7, 3, and 8 completely.",
      "From '682' (1 correct & well placed), 8 is eliminated. Either 6 is in position 1 or 2 is in position 3.",
      "From '206' (2 correct, wrong places), neither 2 nor 6 can be in position 1 or 3.",
      "If 6 was correct in 682, it would be in pos 1; but in 206 it would have to be misplaced, which contradicts. So 6 is eliminated!",
      "Since 6 and 8 are out, 2 is the correct digit in 682 and is in position 3: [ _ , _ , 2 ].",
      "From '206', since 6 is out, 0 is the second correct digit. Since pos 2 is wrong place for 0 in 790, 0 must be in pos 2: [ _ , 0 , 2 ].",
      "From '614' and '431', 1 is correct and goes in pos 1. The code is 102."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_17",
    title: "Concatenated Arithmetic Delta-Sum",
    tier: "foundation",
    domain: "algorithms",
    story: "A cryptographic hash pre-image generator combines differences and sums of input pairs.",
    clue_text: "Analyze the number generation rule:\n7 + 2 = 59   (7-2=5, 7+2=9)\n5 + 3 = 28   (5-3=2, 5+3=8)\n9 + 1 = 810  (9-1=8, 9+1=10)\n8 + 6 = 214  (8-6=2, 8+6=14)\n\nWhat is the value of 7 + 3?",
    payload: "7 + 2 = 59\n5 + 3 = 28\n9 + 1 = 810\n8 + 6 = 214\n7 + 3 = ?\nTASK: Compute 7 + 3 using this pattern.",
    answer: "410",
    aliases: ["410"],
    near_misses: { "10": "Don't just do standard addition! Follow the (A-B)(A+B) pattern.", "47": "7 - 3 = 4 and 7 + 3 = 10, giving 410." },
    hints: [
      "Look at the prefix and suffix of each output.",
      "Prefix is (A - B).",
      "Suffix is (A + B).",
      "For 7 + 3: compute first part = 7 - 3 = 4.",
      "Compute second part = 7 + 3 = 10.",
      "Concatenate the two results: 4 and 10.",
      "Answer: 410."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_18",
    title: "The Expanding Void",
    tier: "foundation",
    domain: "verbal",
    story: "A classic riddle describing an entity defined by absence.",
    clue_text: "\"The more you take away from me, the bigger I become. I weigh absolutely nothing, yet if you put me in a bucket or a hull, I can sink the largest ship.\"\n\nWhat am I?",
    payload: "RIDDLE: The more you take from me, the bigger I get. I weigh nothing, yet I sink ships.\nTASK  : Identify the 4-letter noun.",
    answer: "hole",
    aliases: ["hole", "a hole"],
    near_misses: { "water": "Water has weight! The riddle says 'I weigh absolutely nothing'.", "void": "The classic 4-letter answer found in socks, ground, and boat hulls is a HOLE." },
    hints: [
      "Diggers create it, but it is an absence of matter.",
      "Found in the ground, in a wall, in an argument, and in your sock.",
      "When you take dirt out of it, it expands.",
      "In the hull of a ship, water rushes in through it.",
      "Four letters, starts with 'H'.",
      "H-O-L-E.",
      "Answer: hole."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_19",
    title: "The Cardinal Initial Sequence",
    tier: "foundation",
    domain: "verbal",
    story: "A sequence puzzle based on oral counting in natural language.",
    clue_text: "What is the next letter in this sequence?\n\nO, T, T, F, F, S, S, E, ?",
    payload: "SEQUENCE: O, T, T, F, F, S, S, E, ?\nTASK    : Determine the next letter.",
    answer: "n",
    aliases: ["n", "letter n", "'n'"],
    near_misses: { "t": "Think about counting numbers starting from 1!", "o": "E stands for Eight, what comes after Eight?" },
    hints: [
      "Say numbers out loud starting from 1.",
      "O = One.",
      "T = Two, T = Three.",
      "F = Four, F = Five.",
      "S = Six, S = Seven, E = Eight.",
      "What is the first letter of Nine?",
      "Answer: N."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_20",
    title: "The Reverse Pentavocalic Word",
    tier: "intermediate",
    domain: "verbal",
    story: "A rare linguistic gem where all five English vowels appear exactly in reverse alphabetical order: U, O, I, E, A.",
    clue_text: "Find the 14-letter geographic and geopolitical adjective describing regions like India/South Asia that contains all five standard English vowels in reverse alphabetical order: U -> O -> I -> E -> A.",
    payload: "CRITERIA: Vowels appear in order U, O, I, E, A\nCONTEXT : Pertaining to a large landmass smaller than a continent (e.g., India)\nTASK    : 14-letter word.",
    answer: "subcontinental",
    aliases: ["subcontinental", "unoriental", "subobviation"],
    near_misses: { "continental": "Don't forget the 'sub' prefix that supplies the 'u'!", "subcontinent": "Make sure it includes the final 'a' from '-al'!" },
    hints: [
      "Check the vowels of SUB - CON - TIN - EN - TAL.",
      "s-U-b - c-O-n - t-I-n - e-N-t - A-l.",
      "Vowel 1: U.",
      "Vowel 2: O.",
      "Vowel 3: I.",
      "Vowel 4: E, Vowel 5: A.",
      "The Indian ...",
      "Answer: subcontinental."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_21",
    title: "The Quadruple Strike Nexus",
    tier: "foundation",
    domain: "sleuth",
    story: "A common four-letter noun that holds distinct definitions across alleys, tailoring, arcade games, and combat sports.",
    clue_text: "What single four-letter word connects all four items?\n1. A bowling lane\n2. A tailor's sewing kit\n3. An arcade pinball machine\n4. A victory in a wrestling match",
    payload: "CLUE 1: Bowling lane targets\nCLUE 2: Tailor's sewing fasteners\nCLUE 3: Arcade table bumpers\nCLUE 4: Wrestling winning hold (three-count)\nTASK: Identify the common 4-letter word.",
    answer: "pins",
    aliases: ["pins", "pin"],
    near_misses: { "ball": "You don't ball an opponent in wrestling!", "needle": "Bowling lanes have pins, not needles." },
    hints: [
      "In bowling, you knock down 10 of them.",
      "In tailoring, you use safety ... and sewing ... to hold fabric.",
      "In pinball, the steel ball bounces off bumpers and ...",
      "In wrestling, holding an opponent's shoulders to the mat is called a 'pin'.",
      "Plural: 4 letters.",
      "P-I-N-S.",
      "Answer: pins."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_22",
    title: "Visual Rebus: Confidential Whispers",
    tier: "foundation",
    domain: "lateral",
    story: "A visual idiom captured from an encrypted memo.",
    clue_text: "Examine the layout in the image:\n\nYOU  JUST  ME\n\nWhat classic colloquial English idiom does this arrangement depict?",
    payload: "IMAGE: /puzzles/puzzle_img_2.png\nTEXT : YOU  JUST  ME\nTASK : State the complete English idiom / phrase.",
    media_type: "image",
    media_url: "/puzzles/puzzle_img_2.png",
    answer: "just between you and me",
    aliases: ["just between you and me", "between you and me", "just between us"],
    near_misses: { "you and me": "Where is the word 'JUST' located relative to 'YOU' and 'ME'?", "just you and me": "Notice that 'JUST' is positioned between 'YOU' and 'ME'!" },
    hints: [
      "Where is the word 'JUST' placed?",
      "It is situated between 'YOU' and 'ME'.",
      "A phrase used when sharing a confidential secret.",
      "Five words: Just ... you and me.",
      "Just between you and me.",
      "Answer: just between you and me."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_23",
    title: "The Reducible Octagram Word",
    tier: "intermediate",
    domain: "verbal",
    story: "An 8-letter English word possessing the extraordinary property that deleting one letter at a time can yield a valid dictionary word at each step all the way down to a single letter.",
    clue_text: "What 8-letter English word meaning 'commencing' can have one letter removed at a time to form valid words at 7, 6, 5, 4, 3, 2, and 1 letter?\n\n(Example progression: 8 -> 7 -> 6 -> 5 -> 4 -> 3 -> 2 -> 1)",
    payload: "PROPERTY: Deleting 1 letter successively yields valid words down to a single letter.\nMEANING : Beginning, commencing.\nTASK    : 8-letter word.",
    answer: "starting",
    aliases: ["starting"],
    near_misses: { "start": "That is only 5 letters! The clue asks for the 8-letter word.", "begin": "Check: STARTING -> STARING -> STRING -> STING -> SING -> SIN -> IN -> I." },
    hints: [
      "The word means 'commencing' or 'setting out'.",
      "Look at the chain: STARTING (8).",
      "Remove 't': STARING (7).",
      "Remove 'a': STRING (6).",
      "Remove 'r': STING (5) -> SING (4) -> SIN (3) -> IN (2) -> I (1).",
      "Eight letters, starts with 'S'.",
      "Answer: starting."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_24",
    title: "Hyper-Power Exponential Ladder",
    tier: "foundation",
    domain: "algorithms",
    story: "A sequence of self-exponential powers generated by f(n) = n^n.",
    clue_text: "Find the next integer in this hyper-exponential progression:\n\n1, 4, 27, 256, 3125, ?",
    payload: "1 = 1^1\n4 = 2^2\n27 = 3^3\n256 = 4^4\n3125 = 5^5\nTASK: Compute 6^6.",
    answer: "46656",
    aliases: ["46656", "46,656"],
    near_misses: { "7776": "7776 is 6^5! You need 6^6 = 7776 * 6.", "36": "It is 6 raised to the 6th power." },
    hints: [
      "The formula is n raised to the power of n.",
      "Term 1: 1¹ = 1.",
      "Term 2: 2² = 4.",
      "Term 3: 3³ = 27.",
      "Term 4: 4⁴ = 256; Term 5: 5⁵ = 3125.",
      "Term 6 is 6⁶.",
      "6⁶ = 6 * 6 * 6 * 6 * 6 * 6 = 46,656."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_25",
    title: "Visual Rebus: Creative Exhaustion",
    tier: "foundation",
    domain: "lateral",
    story: "A witty graphic depiction of a runner fleeing from conceptual thoughts.",
    clue_text: "Decode the humorous English idiom shown in this puzzle image.",
    payload: "REBUS IMAGE: /puzzles/puzzle_img_3.png\nTASK: State the full phrase depicted by the graphic.",
    media_type: "image",
    media_url: "/puzzles/puzzle_img_3.png",
    answer: "i ran out of ideas",
    aliases: ["i ran out of ideas", "ran out of ideas", "running out of ideas"],
    near_misses: { "out of ideas": "Include the subject: 'I ran out of ideas'!", "no ideas": "Look at the action: someone ran out." },
    hints: [
      "The letter 'I' is running.",
      "Where is it running from? A cloud / lightbulb / pool of 'ideas'.",
      "I + ran + out + of + ideas.",
      "A phrase said when writer's block strikes.",
      "Five words: I ran out of ...",
      "I ran out of ideas.",
      "Answer: i ran out of ideas."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_26",
    title: "Specular Bilateral Symmetry",
    tier: "foundation",
    domain: "mathematics",
    story: "Geometry and digit reflections in a vertical planar mirror.",
    clue_text: "What is the largest 3-digit number (000 to 999) that remains completely identical when reflected in a vertical mirror?",
    payload: "CRITERION: Vertically symmetric digits (reflected across vertical axis)\nRANGE    : 3-digit integers\nTASK     : Find the maximum integer.",
    answer: "888",
    aliases: ["888"],
    near_misses: { "999": "When 9 is reflected in a vertical mirror, the loop faces left, which is not a valid digit!", "111": "8 is larger than 1 and 0, and 8 has vertical reflective symmetry!" },
    hints: [
      "Which single digits are vertically symmetric? 0, 1 (in sans-serif/digital font), and 8.",
      "Digits like 2, 3, 4, 5, 6, 7, 9 look backwards in a vertical mirror.",
      "Between 0, 1, and 8, which is the largest digit?",
      "8 is the largest vertically symmetric digit.",
      "Combine three of them to form the largest 3-digit number.",
      "888.",
      "Answer: 888."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_27",
    title: "The Pastoral Remainder Paradox",
    tier: "foundation",
    domain: "lateral",
    story: "A classic lateral phrasing trap concerning a shepherd's flock.",
    clue_text: "A farmer has 17 sheep. All but 9 of them run away in a sudden thunderstorm.\n\nHow many sheep are left with the farmer?",
    payload: "TOTAL: 17 sheep\nEVENT: 'All but 9 run away'\nTASK : How many sheep remain?",
    answer: "9",
    aliases: ["9", "nine", "9 sheep"],
    near_misses: { "8": "17 - 9 = 8 is how many ran away! The riddle says 'all BUT 9 ran away'.", "0": "Read carefully: 'All BUT nine'." },
    hints: [
      "Listen closely to the phrase: 'All but 9'.",
      "'All but 9' means that 9 did NOT run away.",
      "Those that did not run away remain with the farmer.",
      "Therefore, exactly 9 sheep stay behind.",
      "17 - 8 = 9.",
      "Answer: 9."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_28",
    title: "Syllogistic Fallacy Identifier",
    tier: "foundation",
    domain: "algorithms",
    story: "Formal logic proposition evaluation involving categorical quantifiers.",
    clue_text: "Premise 1: All roses are flowers.\nPremise 2: Some flowers fade quickly.\n\nCan we validly conclude from these premises alone that some roses fade quickly? (Yes or No)",
    payload: "P1: All A are B\nP2: Some B are C\nCONCLUSION: Some A are C?\nTASK: Answer 'Yes' or 'No'.",
    answer: "no",
    aliases: ["no", "false", "invalid"],
    near_misses: { "yes": "This is the Fallacy of the Undistributed Middle! The flowers that fade quickly might not be roses." },
    hints: [
      "Represent this with Venn diagrams.",
      "The circle of 'Roses' is entirely inside 'Flowers'.",
      "The circle of 'Things that fade quickly' overlaps with 'Flowers'.",
      "Does that overlap necessarily intersect with the 'Roses' subcircle?",
      "No! The flowers that fade quickly could be tulips or daisies, with zero roses fading quickly.",
      "Therefore, the deductive conclusion is invalid.",
      "Answer: no."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_29",
    title: "Visual Rebus: Winter Olympics Sport",
    tier: "foundation",
    domain: "lateral",
    story: "A visual pun depicting numerical figures gliding across ice.",
    clue_text: "Inspect the rebus graphic and identify the elegant Winter Olympic sport.",
    payload: "IMAGE: /puzzles/puzzle_img_4.png\nTASK: Name the sport (two words).",
    media_type: "image",
    media_url: "/puzzles/puzzle_img_4.png",
    answer: "figure skating",
    aliases: ["figure skating", "figureskating"],
    near_misses: { "skating": "Specify the full two-word Olympic discipline!", "ice skating": "Notice the numerical 'figures' (digits) on skates -> Figure Skating!" },
    hints: [
      "What are the numbers shown in the picture? They are 'figures' (digits like 8, 4, etc.).",
      "What footwear do they have on? Ice skates.",
      "Combine 'figure' + 'skating'.",
      "A famous Olympic winter sport featuring axels, lutzes, and spins.",
      "Two words: Figure ...",
      "Answer: figure skating."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_30",
    title: "Orthogonal Closed-Loop Vector",
    tier: "foundation",
    domain: "mathematics",
    story: "A surveyor walks along cardinal unit axes on a flat Euclidean grid.",
    clue_text: "A traveler walks 5 meters North, turns and walks 5 meters West, turns and walks 5 meters South, then turns and walks 5 meters East.\n\nWhere are they relative to their origin point?",
    payload: "VECTORS: +5j, -5i, -5j, +5i\nTASK: Describe their final position (one word or key term).",
    answer: "start",
    aliases: ["start", "starting point", "origin", "at the start", "where they started"],
    near_misses: { "5m north": "Check your math: 5 North and 5 South cancel out!", "west": "5 West and 5 East cancel out." },
    hints: [
      "Look at the North-South axis: +5 North, then -5 South. Net displacement = 0.",
      "Look at the East-West axis: -5 West, then +5 East. Net displacement = 0.",
      "The total vector sum: (0, 0).",
      "They have traversed a complete square.",
      "They have returned to the exact location they began.",
      "Answer: start."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_31",
    title: "Geometric System of Equations",
    tier: "foundation",
    domain: "algorithms",
    story: "A system of linear algebraic equations masked as geometric glyphs.",
    clue_text: "Given the simultaneous system:\n▲ + ▲ = ■\n■ + ▲ = 12\n\nWhat is the numerical value of ▲?",
    payload: "2 * ▲ = ■\n■ + ▲ = 12\nTASK: Find ▲.",
    answer: "4",
    aliases: ["4", "four"],
    near_misses: { "8": "8 is the value of the square (■), not the triangle (▲)!", "6": "Substitute ■ = 2▲ into the second equation: 2▲ + ▲ = 3▲ = 12." },
    hints: [
      "Let ▲ = x.",
      "From equation 1: ■ = x + x = 2x.",
      "Substitute ■ into equation 2: 2x + x = 12.",
      "3x = 12.",
      "Divide both sides by 3.",
      "x = 12 / 3 = 4.",
      "Answer: 4."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_32",
    title: "The Thermodynamic Tea Mystery",
    tier: "intermediate",
    domain: "lateral",
    story: "A forensic sleuth puzzle where two patrons drink identical poisoned tea from the same pitcher.",
    clue_text: "Sarah and Jane order iced tea from the same pitcher at a cafe. Sarah drinks five glasses rapidly in five minutes. Jane sips slowly on a single glass over an hour. Jane dies of poisoning, while Sarah suffers no ill effects. Forensic analysis proves the liquid tea in the pitcher was pure.\n\nWhere was the poison hidden?",
    payload: "MYSTERY: Identical pitcher, one drinks fast and lives, one drinks slow and dies.\nTASK   : State where the poison was contained (1-3 words).",
    answer: "ice",
    aliases: ["ice", "the ice", "in the ice", "ice cubes", "in the ice cubes", "the poison was in the ice"],
    near_misses: { "glass": "Both glasses were washed and identical from the shelf.", "straw": "Neither used a poisoned straw; the substance was temperature-bound." },
    hints: [
      "Both women were served cold iced tea.",
      "Sarah drank hers so fast that something in the drink didn't have time to melt.",
      "Jane waited an hour while her drink sat at room temperature.",
      "As time passed, a solid ingredient changed phase into liquid.",
      "The poison was frozen inside the ice cubes.",
      "Sarah drank before the ice melted; Jane drank after the ice melted.",
      "Answer: ice."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_33",
    title: "The Morphological Matryoshka Word",
    tier: "foundation",
    domain: "verbal",
    story: "A single 7-letter English word whose progressive prefixes yield gendered and heroic concepts.",
    clue_text: "Find the 7-letter English word where:\n- The first 2 letters denote a male (2 letters)\n- The first 3 letters denote a female (3 letters)\n- The first 4 letters denote a great man / champion (4 letters)\n- The entire 7 letters denote a great woman / female champion\n\nWhat is the word?",
    payload: "1-2: Male\n1-3: Female\n1-4: Great man\n1-7: Great woman\nTASK: Enter the 7-letter word.",
    answer: "heroine",
    aliases: ["heroine"],
    near_misses: { "hero": "Hero is only 4 letters! The clue asks for the full 7-letter word denoting a great woman.", "heroin": "Heroin is a drug (6 letters); Heroine is the female champion (7 letters)." },
    hints: [
      "First 2 letters: HE (male).",
      "First 3 letters: HER (female).",
      "First 4 letters: HERO (great man / champion).",
      "Now add three letters to complete the female champion.",
      "H - E - R - O - I - N - E.",
      "A female protagonist or champion.",
      "Answer: heroine."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_34",
    title: "The Fast-Forward Clock",
    tier: "foundation",
    domain: "systems",
    story: "A clock mechanism with an accelerated balance wheel.",
    clue_text: "A clock gains 15 minutes every hour. It is set correctly at 9:00 AM.\n\nWhen the true time is 1:00 PM on the same day, what time does this clock show?",
    payload: "RATE: +15 minutes per real hour\nSTART: 9:00 AM\nREAL TIME: 1:00 PM (4 hours elapsed)\nTASK: Output the displayed clock time (e.g. 2 PM or 2:00 PM).",
    answer: "2 pm",
    aliases: ["2 pm", "2:00 pm", "2pm", "2:00pm", "14:00", "2"],
    near_misses: { "12 pm": "The clock GAINS time, so it runs ahead of real time, not behind!", "1:45 pm": "4 hours * 15 min/hr = 60 minutes gain!" },
    hints: [
      "The clock gains 15 minutes each hour.",
      "From 9:00 AM to 1:00 PM is 4 hours.",
      "Total minutes gained = 4 * 15 = 60 minutes.",
      "60 minutes = 1 full hour gained.",
      "Add 1 hour to the true time of 1:00 PM.",
      "1:00 PM + 1 hour = 2:00 PM.",
      "Answer: 2 PM."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_35",
    title: "Visual Rebus: Synthetic Cognition",
    tier: "foundation",
    domain: "lateral",
    story: "A visual glyph representing the frontier of computational intelligence.",
    clue_text: "Decipher the iconic technological two-letter abbreviation shown in this puzzle image.",
    payload: "IMAGE: /puzzles/puzzle_img_5.png\nTASK: Identify the 2-letter abbreviation.",
    media_type: "image",
    media_url: "/puzzles/puzzle_img_5.png",
    answer: "ai",
    aliases: ["ai", "artificial intelligence"],
    near_misses: { "ml": "The image features the classic two letters A and I!", "it": "Look at the letters: A and I." },
    hints: [
      "The image clearly spells two letters.",
      "The first letter is 'A', the second is 'I'.",
      "Short for Artificial Intelligence.",
      "Powers neural networks, LLMs, and robotics.",
      "Two letters: A - I.",
      "Answer: ai."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_36",
    title: "The Inverse Luminance Phenomenon",
    tier: "foundation",
    domain: "verbal",
    story: "A riddle of light, perception, and photons.",
    clue_text: "\"The more of me there is, the less you see.\"\n\nWhat am I?",
    payload: "RIDDLE: The more of me there is, the less you see.\nTASK  : Identify the 8-letter condition of no light.",
    answer: "darkness",
    aliases: ["darkness", "dark", "fog"],
    near_misses: { "light": "More light makes things easier to see (unless blinding)! Absence of light reduces vision.", "blindness": "The environmental condition of having zero light is darkness." },
    hints: [
      "Occurs when the sun sets and artificial lights are switched off.",
      "Photons are absent.",
      "Eight letters, starts with 'D'.",
      "Opposite of brightness / light.",
      "D-A-R-K-N-E-S-S.",
      "Answer: darkness."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_37",
    title: "Chinese Remainder Diophantine",
    tier: "foundation",
    domain: "algorithms",
    story: "A modular arithmetic modular residue problem.",
    clue_text: "A jar contains a collection of marbles. When divided into groups of 5, there are 3 marbles left over. When divided into groups of 4, there are 2 marbles left over.\n\nWhat is the SMALLEST positive number of marbles that satisfies both conditions?",
    payload: "SYSTEM: N = 3 mod 5 and N = 2 mod 4\nCRITERIA: Smallest positive integer N > 0\nTASK: Compute N.",
    answer: "18",
    aliases: ["18"],
    near_misses: { "8": "8 mod 5 = 3, but 8 mod 4 = 0 (we need remainder 2)!", "38": "38 satisfies both, but 18 is smaller!" },
    hints: [
      "Numbers giving remainder 3 modulo 5: 3, 8, 13, 18, 23, 28...",
      "Test each with modulo 4:",
      "3 mod 4 = 3 (not 2).",
      "8 mod 4 = 0 (not 2).",
      "13 mod 4 = 1 (not 2).",
      "18 mod 4 = 2 (matches!). And 18 mod 5 = 3 (matches!).",
      "Smallest solution: 18.",
      "Answer: 18."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_38",
    title: "The Unperceived Container Riddle",
    tier: "foundation",
    domain: "verbal",
    story: "A somber riddle dating back to antiquity.",
    clue_text: "\"The person who makes it, sells it. The person who buys it, never uses it. The person who uses it, never sees it.\"\n\nWhat is it?",
    payload: "RIDDLE: Maker sells it, buyer doesn't use it, user never sees it.\nTASK  : Identify the 6-letter object.",
    answer: "coffin",
    aliases: ["coffin", "a coffin", "casket"],
    near_misses: { "tombstone": "A tombstone is placed above ground; the body is inside a coffin!", "shroud": "The classic English riddle answer is a coffin." },
    hints: [
      "The maker is a carpenter.",
      "The buyer purchases it for a deceased loved one.",
      "The person who occupies it is no longer alive, so they cannot see it.",
      "Starts with 'C', six letters.",
      "C-O-F-F-I-N.",
      "Answer: coffin."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_39",
    title: "The Museum Heist Deduction",
    tier: "intermediate",
    domain: "sleuth",
    story: "A jewel was stolen from a locked museum display case at 2:15 AM. Four guards were interrogated.",
    clue_text: "Four security guards testify:\n- Guard A: \"I was watching the east door all night.\"\n- Guard B: \"I never left the security room.\"\n- Guard C: \"I was on my break from 2:00 to 2:30 AM.\"\n- Guard D: \"The theft happened exactly at 2:15 AM, and I saw it on camera.\"\n\nDetective notes confirm all camera monitor feeds are located exclusively inside the security room. Who is lying?",
    payload: "WITNESSES: Guard A, Guard B, Guard C, Guard D\nCLUE     : Camera monitors are ONLY inside the security room.\nTASK     : Name the lying guard (e.g., 'Guard B').",
    answer: "guard b",
    aliases: ["guard b", "b"],
    near_misses: { "guard d": "Guard D saw it on camera; if B was in the security room the whole time, B would have seen it too or D wasn't alone!", "guard c": "Guard C was verified on break." },
    hints: [
      "The monitors are in the security room.",
      "Guard D claims to have watched the theft live on the camera at 2:15 AM.",
      "Guard B claims they never left the security room at any point.",
      "If B never left the room, B would have either seen D watching the theft, seen the theft on screen, or seen D enter.",
      "B is either lying about being in the security room, or covering up the crime.",
      "The lying guard is Guard B.",
      "Answer: guard b."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_40",
    title: "Exponential Doubling Lily Pad",
    tier: "foundation",
    domain: "mathematics",
    story: "A classic cognitive trap regarding exponential bacterial and lily pad growth.",
    clue_text: "A lily pad patch in a pond doubles in surface area every single day. It takes exactly 48 days for the patch to completely cover the entire pond.\n\nOn what day was the pond exactly HALF covered?",
    payload: "DOUBLING: Area(t) = 2 * Area(t - 1)\nFULL COVERAGE: Day 48\nTASK: Determine the day when area was 1/2 of full.",
    answer: "47",
    aliases: ["47", "day 47"],
    near_misses: { "24": "Half of 48 is 24, but growth is exponential, not linear! On day 24 it covered less than 0.00001% of the pond.", "46": "On day 46 it was one-quarter covered." },
    hints: [
      "Since the patch doubles every single day, look at it backwards.",
      "If the pond is completely full on day 48...",
      "What fraction of the pond was covered exactly ONE day earlier?",
      "Half of full!",
      "Day 48 - 1 day = Day 47.",
      "On Day 47, half the pond is covered, which doubles to 100% on Day 48.",
      "Answer: 47."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_41",
    title: "The Homophonic Query Grapheme",
    tier: "foundation",
    domain: "verbal",
    story: "A letter whose phonetic pronunciation doubles as an inquiry of comprehension.",
    clue_text: "What single letter of the English alphabet, when spoken aloud, sounds like a complete question asking about clarity of vision or comprehension?",
    payload: "CRITERION: Single English letter\nPHONETIC : Sounds like 'See?' (Do you see / understand?)\nTASK     : State the letter.",
    answer: "c",
    aliases: ["c", "letter c", "'c'"],
    near_misses: { "u": "'U' sounds like 'You', which is not a question of clarity.", "y": "'Why' is a question of reason, not clarity of sight!" },
    hints: [
      "Think of the verb for vision: to see.",
      "Pronounced identically to the third letter of the alphabet.",
      "Used colloquially: 'See?' meaning 'Do you understand?'.",
      "Letter between B and D.",
      "Answer: C."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_42",
    title: "Progressive Anagrammatic Chain",
    tier: "foundation",
    domain: "verbal",
    story: "A 5-step linguistic chain starting from a single letter.",
    clue_text: "Trace the 5-step valid word chain:\nStep 1: I (1 letter)\nStep 2: IT (add T)\nStep 3: SIT (add S)\nStep 4: SITE (add E)\nStep 5: Rearrange 'SITE' and add the letter 'U' to form a luxury hotel accommodation.\n\nWhat is the final 5-letter word?",
    payload: "CHAIN: I -> IT -> SIT -> SITE -> (SITE + U rearranged)\nCLUE : A luxury hotel room / software suite\nTASK : State the 5-letter word.",
    answer: "suite",
    aliases: ["suite", "suites"],
    near_misses: { "suit": "That is only 4 letters! The clue specifies a 5-letter word containing S, I, T, E, and U.", "etuis": "While valid, the common English word for hotel accommodation is SUITE." },
    hints: [
      "The letters available are: S, I, T, E, and U.",
      "Pronounced like 'sweet'.",
      "A connected series of rooms in a luxury hotel.",
      "Also used in computing: office ... or test ...",
      "S-U-I-T-E.",
      "Answer: suite."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_43",
    title: "The Horological Mirror Inversion",
    tier: "foundation",
    domain: "mathematics",
    story: "A mirror reflection of an analog 12-hour clock face.",
    clue_text: "You look at an analog 12-hour clock in a mirror. The reflected image appears to show the time 6:15.\n\nWhat is the ACTUAL real time shown on the clock on the wall?",
    payload: "MIRROR IMAGE TIME: 6:15\nREFLECTION AXIS  : Vertical (12 and 6 stay vertical, left and right invert)\nTASK             : Compute the real time (HH:MM).",
    answer: "5:45",
    aliases: ["5:45", "5.45", "5:45 pm", "5:45 am"],
    near_misses: { "6:45": "Check the hour hand! At 6:15, the hour hand is past 6, so in the mirror it is before 6 (in the 5 o'clock hour).", "6:15": "The mirror flips horizontal positions." },
    hints: [
      "In a vertical mirror, 12:00 corresponds to 12:00.",
      "The general formula for real time from mirror reflection is: 11:60 - (mirror time) or 12:00 - (mirror time).",
      "Subtract 6:15 from 11:60:",
      "Hours: 11 - 6 = 5.",
      "Minutes: 60 - 15 = 45.",
      "Real time: 5:45.",
      "Answer: 5:45."
    ],
    points: 1000
  },
  {
    code: "NODE_ADD_44",
    title: "Handshake Combinatorics & Atlantic City Ruin",
    tier: "foundation",
    domain: "algorithms",
    story: "Two distinct classical logic puzzles: complete graph edges K_12, and a famous board game financial collapse.",
    clue_text: "Part 1: In a room of 12 people, every person shakes hands once with every other person. The total number of handshakes is C(12, 2) = (12 * 11) / 2.\nPart 2: A man pushes his miniature car token past a red hotel property and instantly realizes he is bankrupt.\n\nWhat is the total number of handshakes in Part 1?",
    payload: "PART 1: Handshakes among 12 people = 12 * 11 / 2\nPART 2: Trivia reference to Monopoly\nTASK  : Enter the integer number of handshakes.",
    answer: "66",
    aliases: ["66", "66 handshakes", "monopoly"],
    near_misses: { "72": "12 * 6 = 72, but n*(n-1)/2 = 12*11/2 = 66!", "60": "Compute: 12 * 11 = 132; 132 / 2 = 66." },
    hints: [
      "Each of the 12 people shakes hands with 11 others.",
      "Total pairs = 12 * 11 = 132.",
      "Since a handshake between Alice and Bob is the same as Bob and Alice, divide by 2.",
      "132 / 2 = 66.",
      "Answer: 66."
    ],
    points: 1000
  }
];
